# Generated by Django 3.1.1 on 2020-10-14 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppWall', '0002_auto_20201014_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='user_id',
            new_name='commenting_user',
        ),
    ]
